import { NextPage } from "next"
import { Head } from "next/document"
import NavBar from "./NavBar"

export const ProjectMenu: NextPage = () => {
    return (
      <div>
        <Head>
          <title>Ethan Husband: Blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
       <NavBar />
  
        <main>
        <div className="flex flex-col p-6 rounded-lg w-auto mt-48 bg-gray-600 mx-24">
          <h1>Latest Posts</h1>
          <ul>  
              <li>How Group Theory Can Speed Up Hashing Algorithms</li>
              <li>How Quantum Computers Mark Solutions</li>
              <li>Classing Holomorphic Complex Functions</li>
              <li>How Is e Irrational?</li>
              <li>The Fairness of Allocating To a Prime Number of People</li>
              {/** 
               * How To Make a Developer Blog (Like This)
               * How To Setup Prisma and PlanetScale SQL databases
               * How To Setup an independent GraphQL server
               * How To Get Auth For Your App
               * Automating Business Decisions with Game Theory and Microeconomics
               * Understanding the Riemann Zeta conjecture (prime number proof, all zeros in [0,1])
               */}
          </ul>
        </div>
        </main>
      </div>
    )
  }
  
