import { NextPage } from 'next'
import { Main } from 'next/document'
import Head from 'next/head'
import NavBar from './NavBar'

export const ProjectMenu: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Ethan Husband: Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <NavBar />

      <main>
      <div className="flex flex-col p-6 rounded-lg w-auto mt-48 bg-gray-600 mx-24">
        <h1>Projects</h1>
        <ul>  
            <li>Twitter Follower Data Analysis</li>
            <li>This Website</li>
            <li>Dynamic Load Balancing (EV chargers)</li>
            <li>2048 Bot</li>
            <li>EVUp Charge</li>
            <li>A Basic Checkers Bot in C</li>
        </ul>
      </div>
      </main>
    </div>
  )
}

const Project = () => {

}

export default ProjectMenu;
