import Link from 'next/link'
import Head from 'next/head'

export const SitePage = ({ children }: any) => {
  return (
    <div className="w-screen bg-primary h-screen cursor-crosshair">
      <Head>
        <title>Ethan Husband</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <div className="px-24 py-20">{children}</div>
    </div>
  )
}

export const NavBar = () => {
  return (
    <div className="z-50 fixed top-0 right-0 left-0 bg-black mx-auto rounded-b-3xl fixedAWSD border-secondary border-b white-shadow">
      <ul className="text-secondary font-semibold px-8 py-5 flex flex-row gap-x-12 justify-center">
        <Link href="/Blog">
          <li className="button-hover">Blog</li>
        </Link>
        <Link href="/Projects">
          <li className="button-hover">Projects</li>
        </Link>
        <Link href="/About">
          <li className="button-hover">About</li>
        </Link>
        <li className="button-hover">CV</li>
      </ul>
    </div>
  )
}

export default SitePage
